language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  email:
    recipients:
      - jm.tena01@hotmail.com
      
script: mvn verify
