language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  email:
    recipients:
      - jm.tena01@hotmail.com
      
<<<<<<< HEAD
script: mvn verify
=======
script: mvn verify
>>>>>>> refs/heads/develop
